In [4]:
# PYPDF2
import PyPDF2

In [5]:
with open('electro.pdf', 'rb') as f:
    reader = PdfFileReader(f)
    contents = reader.getPage(0).extractText()
    pass

NameError: name 'PdfFileReader' is not defined

In [7]:
file = open('electro.pdf', 'rb')
fileReader = PyPDF2.PdfFileReader(file)
page = fileReader.getPage(133)
page.extractText

<bound method PageObject.extractText of {'/Tabs': '/S', '/Type': '/Page', '/Group': {'/S': '/Transparency', '/CS': '/DeviceRGB', '/Type': '/Group'}, '/Parent': IndirectObject(4, 0), '/Contents': IndirectObject(686, 0), '/MediaBox': [0, 0, 595.32, 841.92], '/Resources': {'/Font': {'/F2': IndirectObject(670, 0), '/F3': IndirectObject(671, 0), '/F4': IndirectObject(672, 0), '/F5': IndirectObject(673, 0), '/F6': IndirectObject(675, 0)}, '/ProcSet': ['/PDF', '/Text', '/ImageB', '/ImageC', '/ImageI']}, '/StructParents': 12}>

In [8]:
df

NameError: name 'df' is not defined

In [65]:
#TABULA

import tabula

import pandas as pd

In [104]:
# опции guess и lattice - могут влиять на качество распознавания. 
for i in range (135, 142):
    df = tabula.read_pdf("electro.pdf", pages=i, guess = False, lattice = True)
    df.iloc[:,3:]=df.iloc[:,3:].apply(lambda x: x.str.replace(',','.')).astype(float)

    #df.iloc[:,10] = ''
    df.to_excel('output'+str(i)+'.xlsx')

AttributeError: ('Can only use .str accessor with string values, which use np.object_ dtype in pandas', 'occurred at index 2024 год')

In [ ]:
# эта часть кода дает возможность конвертировать элементы датафрейма из строк в числа "на лету", не сжимая размерность
df.iloc[:,3:]=df.iloc[:,3:].apply(lambda x: x.str.replace(',','.')).astype(float)

In [50]:
df.iloc[:,3:10] = df.iloc[:,3:10].str.replace(',','.')

AttributeError: 'DataFrame' object has no attribute 'str'

In [86]:
df

,"Электростанция (станционный номер, тип турбины)",Генерирующая компания,Вид топлива,2019 год,2020 год,2021 год,2022 год,2023 год,2024 год,2025 год,2019-2025 годы
0,"ТЭС ЗАО ""ВНХК""","АО ""Восточная",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1 ПГУ(Т),"нефтехимическая компания""",Газ,NaN,NaN,NaN,NaN,NaN,NaN,122.0,122.0
2,2 ПГУ(Т),NaN,Газ,NaN,NaN,NaN,NaN,NaN,NaN,122.0,122.0
3,3 ПГУ(Т),NaN,Газ,NaN,NaN,NaN,NaN,NaN,NaN,122.0,122.0
4,4 ГТ-77(Т),NaN,Газ,NaN,NaN,NaN,NaN,NaN,NaN,77.0,77.0
5,5 ГТ-77(Т),NaN,Газ,NaN,NaN,NaN,NaN,NaN,NaN,77.0,77.0
6,Всего по станции,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,520.0,520.0
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Энергосистема Хабаровского края,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Хабаровская ТЭЦ-4,"ПАО ""РусГидро""",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,1 ПГУ ТЭЦ,NaN,Газ,NaN,NaN,NaN,NaN,111.0,NaN,NaN,111.0
11,2 ПГУ ТЭЦ,NaN,Газ,NaN,NaN,NaN,NaN,111.0,NaN,NaN,111.0
12,3 ПГУ ТЭЦ,NaN,Газ,NaN,NaN,NaN,NaN,111.0,NaN,NaN,111.0
13,Всего по станции,NaN,NaN,NaN,NaN,NaN,NaN,333.0,NaN,NaN,333.0
14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,ТЭЦ города Советская Гавань,"ПАО ""РусГидро""",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,"1 ТФ-63-13/0,25",NaN,Уголь,63.0,NaN,NaN,NaN,NaN,NaN,NaN,63.0
17,"2 ТФ-63-13/0,25",NaN,Уголь,63.0,NaN,NaN,NaN,NaN,NaN,NaN,63.0
18,Всего по станции,NaN,NaN,126.0,NaN,NaN,NaN,NaN,NaN,NaN,126.0
19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,Энергосистема Республики Саха-\rЯкутия,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,"ТЭЦ ООО ""Газпром добыча Ноябрьск""","ООО ""Газпром добыча\rНоябрьск""",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,1 ГТ-12(Т),NaN,Газ,NaN,NaN,NaN,NaN,12.0,NaN,NaN,12.0
23,2 ГТ-12(Т),NaN,Газ,NaN,NaN,NaN,NaN,12.0,NaN,NaN,12.0
24,3 ГТ-12(Т),NaN,Газ,NaN,NaN,NaN,NaN,12.0,NaN,NaN,12.0
25,4 ГТ-12(Т),NaN,Газ,NaN,NaN,NaN,NaN,12.0,NaN,NaN,12.0
26,5 ГТ-12(Т),NaN,Газ,NaN,NaN,NaN,NaN,12.0,NaN,NaN,12.0
27,6 ГТ-12(Т),NaN,Газ,NaN,NaN,NaN,NaN,12.0,NaN,NaN,12.0
28,Всего по станции,NaN,NaN,NaN,NaN,NaN,NaN,72.0,NaN,NaN,72.0
29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,"ОЭС Востока, всего",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,ТЭС,NaN,NaN,126.0,160.0,NaN,NaN,405.0,240.0,520.0,1451.0
32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,ЕЭС России - всего,NaN,NaN,4200.9,1835.1,2300.7,1586.9,2126.4,1440.0,1670.0,15160.0
34,АЭС,NaN,NaN,1150.0,NaN,1150.0,NaN,1200.0,1200.0,1150.0,5850.0
35,ГЭС и малые ГЭС,NaN,NaN,416.7,16.0,24.9,24.9,23.7,NaN,NaN,506.2
36,ГАЭС,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,ТЭС,NaN,NaN,1252.0,884.0,225.0,875.0,405.0,240.0,520.0,4401.0
38,ВИЭ,NaN,NaN,1382.3,935.1,900.8,687.0,497.7,NaN,NaN,4402.9
39,ветровые,NaN,NaN,748.8,640.1,737.8,530.0,497.7,NaN,NaN,3154.4
40,солнечные,NaN,NaN,633.5,295.0,163.0,157.0,NaN,NaN,NaN,1248.5

In [13]:
import pandas as pd

In [88]:
years = pd.DataFrame(df.iloc[:40,2]).copy()

In [89]:
years.drop(index=[0,1], inplace=True)
years.reset_index(drop = True, inplace=True)
years

   real GDP indexes
0               1 1
1   1.08492 1.06563
2   1.07269 1.03576
3   1.01970 0.96861
4   1.00272 0.93758
5   1.02718 0.94590
6   1.08289 0.98250
7   1.17256 1.04850
8   1.27039 1.11983
9   1.27786 1.11057
10  1.33493 1.14391
11  1.34308 1.13477
12  1.29553 1.07917
13  1.34580 1.10508
14  1.38316 1.11936
15  1.51360 1.20693
16  1.58901 1.24804
17  1.74934 1.35285
18  1.77448 1.35065
19  1.79962 1.34756
20  1.69704 1.24952
21  1.72625 1.24916
22  1.81457 1.28993
23  1.79215 1.25115
24  1.85193 1.26941
25  1.91987 1.29192
26  1.88183 1.24310
27  1.86485 1.20932
28  1.99257 1.26860
29  2.04488 1.27839
30  1.98985 1.22180
31  2.04284 1.23226
32  2.12776 1.26104
33  2.11010 1.22865
34  2.29828 1.31449
35  2.17260 1.22017
36  2.22016 1.22379
37  2.18280 1.18023

In [99]:
years1 = pd.DataFrame(df.iloc[:40,5]).copy()
years1.drop(index=[0,1], inplace=True)
years1.reset_index(drop = True, inplace=True)
years1.rename(columns={'real GDP indexes.1':'real GDP indexes'}, inplace=True)
years1

   real GDP indexes
0   2.14000 1.13422
1   2.20046 1.14232
2   2.45862 1.24904
3   2.66922 1.32585
4   2.37098 1.15067
5   2.06730 0.97974
6   2.11553 0.97874
7   2.57138 1.16115
8   2.38591 1.05160
9   2.40561 1.03504
10  2.52654 1.06149
11  2.53605 1.04081
12  2.50616 1.00523
13  2.80018 1.09833
14  2.99619 1.14979
15  3.01019 1.13063
16  3.02419 1.11211
17  3.09419 1.11429
18  3.23420 1.14077
19  3.68223 1.27222
20  3.31821 1.12302
21  3.66823 1.21606
22  3.93425 1.27744
23  3.94825 1.25547
24  4.36828 1.36018
25  4.43828 1.35317
26  4.49428 1.34165
27  4.43828 1.29726
28  4.63429 1.32630
29  4.88631 1.36932
30  4.98432 1.36780
31  5.27834 1.41856
32  5.81037 1.52944
33  5.92238 1.52707
34  6.38441 1.61274
35  6.93045 1.71525
36  7.02846 1.70447
37  7.02846 1.67025

In [91]:
years2 = pd.DataFrame(df.iloc[41:81,2]).copy()
years2.drop(index=[41,42], inplace=True)
years2.reset_index(drop = True, inplace=True)
years2

    real GDP indexes
0     7.39248 1.7216
1    8.19053 1.86938
2    9.12859 2.04198
3    9.22660 2.02287
4    9.03059 1.94059
5    8.73657 1.84017
6    9.11459 1.88170
7    9.92664 2.00865
8   10.83670 2.14914
9   11.15872 2.16881
10  12.50281 2.38132
11  13.07685 2.44049
12  13.66489 2.49858
13  14.00091 2.50787
14  13.86090 2.43190
15  14.54694 2.49953
16  14.15491 2.38125
17  15.35899 2.52866
18  16.52106 2.66053
19  17.05309 2.68448
20  19.02722 2.92579
21  19.48925 2.92499
22  21.37971 3.12905
23  23.02595 3.28326
24  24.59171 3.41294
25  25.79670 3.48125
26  27.67986 3.62920
27  28.98081 3.68939
28  31.24131 3.85979
29  33.99055 4.07416
30  34.97628 4.06645
31  37.66945 4.24776
32  41.73775 4.56503
33  45.82805 4.86235
34  50.13589 5.16128
35  54.44758 5.44006
36  58.04112 5.63000
37  58.38937 5.50033

In [100]:
years3 = pd.DataFrame(df.iloc[41:81,5]).copy()
years3.drop(index=[41,42], inplace=True)
years3.reset_index(drop = True, inplace=True)
years3.rename(columns={'real GDP indexes.1':'real GDP indexes'}, inplace=True)

In [101]:
ally = pd.concat([years,years1,years2,years3], axis = 0, ignore_index=True)

In [102]:
ally

       real GDP indexes
0                   1 1
1       1.08492 1.06563
2       1.07269 1.03576
3       1.01970 0.96861
4       1.00272 0.93758
5       1.02718 0.94590
6       1.08289 0.98250
7       1.17256 1.04850
8       1.27039 1.11983
9       1.27786 1.11057
10      1.33493 1.14391
11      1.34308 1.13477
12      1.29553 1.07917
13      1.34580 1.10508
14      1.38316 1.11936
15      1.51360 1.20693
16      1.58901 1.24804
17      1.74934 1.35285
18      1.77448 1.35065
19      1.79962 1.34756
20      1.69704 1.24952
21      1.72625 1.24916
22      1.81457 1.28993
23      1.79215 1.25115
24      1.85193 1.26941
25      1.91987 1.29192
26      1.88183 1.24310
27      1.86485 1.20932
28      1.99257 1.26860
29      2.04488 1.27839
..                  ...
122   113.71590 8.35358
123   129.60056 9.27780
124   140.16811 9.78303
125  147.41011 10.03576
126  162.53016 10.79893
127  170.54993 11.06516
128  179.02609 11.34820
129  191.12747 11.84381
130  208.71120 12.65122
131  199.84097 11.85639
132  201.49965 11.70773
133  195.59571 11.13577
134  206.15788 11.50641
135  222.34127 12.17141
136  238.99463 12.83743
137  247.43114 13.04635
138  247.28268 12.80374
139  255.09681 12.97505
140  244.00010 12.19542
141  246.51864 12.11133
142  245.17741 11.84351
143  257.25164 12.22166
144  272.30824 12.72657
145  283.80997 13.05133
146  291.35531 13.18613
147  300.88668 13.40445
148  301.28361 13.21450
149  303.72994 13.11786
150  316.97937 13.48256
151                -  -

[152 rows x 1 columns]

In [103]:
ally.to_excel("output.xlsx",sheet_name='Sheet_name_1')